export const dataBase = [
  {
    id: 0,
    bookName: "JAVA For  Beginners",
    author: "NATHAN METZLER",
    price: "$20",
    rating: "3",
    img: "./assets/JAVA For  Beginners.png",
  },
  {
    id: 1,
    bookName: "Cracking the Coding Interview",
    author: "Gayle Laakmann McDowell",
    price: "$60",
    rating: "4.5",
    img: "./assets/Cracking the Coding Interview.jpg",
  },
  {
    id: 2,
    bookName: "Programming in Short Stories",
    author: "Moinul Raju",
    price: "$10",
    rating: "4.1",
    img: "./assets/Programming in Short Stories.jpg",
  },
  {
    id: 3,
    bookName: "Php: The Complete Reference",
    author: "Steven Holzner",
    price: "$13",
    rating: "5",
    img: "./assets/php the complete.gif",
  },
  {
    id: 4,
    bookName: "Data Structures and Algorithms",
    author: "Zakir Hossain",
    price: "$4",
    rating: "4.2",
    img: "./assets/Pythone_Data_Structure_o_Algorithm-Jakir_Hossain-7d02e-284838.jpg",
  },
  {
    id: 6,
    bookName: "Object Oriented Programming",
    author: "Robert Lafore",
    price: "$20",
    rating: "4.9",
    img: "./assets/Object Oriented Programming.gif",
  },
  {
    id: 7,
    bookName: "Programming Career Guide Lines",
    author: "Tamim Shahriar Subin",
    price: "$2.3",
    rating: "3.8",
    img: "./assets/Programming Career Guide Lines.jpg",
  },
  {
    id: 8,
    bookName: "Machine Learning Algorithms",
    author: "Nafis Nihal",
    price: "$10",
    rating: "4.6",
    img: "./assets/Machine Learning Algorithms.jpg",
  },
];
